name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby_version: [ruby-head, '3.3', '3.2', '3.1', '3.0', '2.7']
        rails_version: [edge, '7.0', '6.1']

        include:
          - ruby_version: '3.1'
            activemodel_version: '7.0'

          - ruby_version: '3.0'
            rails_version: '6.0'
          - ruby_version: '3.0'
            activemodel_version: '6.1'

          - ruby_version: '2.7'
            rails_version: '6.0'
          - ruby_version: '2.7'
            activemodel_version: '6.0'

          - ruby_version: '2.6'
            rails_version: '5.2'
          - ruby_version: '2.6'
            activemodel_version: '5.2'
          - ruby_version: '2.6'
            rails_version: '5.1'
          - ruby_version: '2.6'
            rails_version: '5.0'
          - ruby_version: '2.6'
            rails_version: '4.2'

          - ruby_version: '2.5'
            rails_version: '5.2'

          - ruby_version: '2.4'
            rails_version: '4.2'

          - ruby_version: '2.3'
            rails_version: '4.2'
          - ruby_version: '2.3'
            rails_version: '4.1'
          - ruby_version: '2.3'
            rails_version: '4.0'

          - ruby_version: '2.2'
            rails_version: '4.2'

          - ruby_version: '2.1'
            rails_version: '3.2'

    runs-on: ubuntu-24.04

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      RAILS_VERSION: ${{ matrix.rails_version }}
      ACTIVEMODEL_VERSION: ${{ matrix.activemodel_version }}

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          rubygems: ${{ matrix.ruby_version < '2.6' && 'default' || 'latest' }}
          bundler: ${{ (contains(matrix.gemfile, 'rails_4') || contains(matrix.gemfile, 'rails_3')) && '1' || '2' }}
          bundler-cache: true
        continue-on-error: ${{ (matrix.ruby_version == 'ruby-head') || (matrix.rails_version == 'edge') || (matrix.allow_failures == 'true') }}

      - run: bundle exec rake
        continue-on-error: ${{ (matrix.ruby_version == 'ruby-head') || (matrix.rails_version == 'edge') || (matrix.allow_failures == 'true') }}
